// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package schema

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type GetHardwarePool struct {
	_tab flatbuffers.Table
}

func GetRootAsGetHardwarePool(buf []byte, offset flatbuffers.UOffsetT) *GetHardwarePool {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &GetHardwarePool{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *GetHardwarePool) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *GetHardwarePool) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *GetHardwarePool) Hardware(j int) []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.ByteVector(a + flatbuffers.UOffsetT(j*4))
	}
	return nil
}

func (rcv *GetHardwarePool) HardwareLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func GetHardwarePoolStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func GetHardwarePoolAddHardware(builder *flatbuffers.Builder, hardware flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(hardware), 0)
}
func GetHardwarePoolStartHardwareVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func GetHardwarePoolEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
