version: "3.7"
services:
  #Don't run all containers on the same device, the port bindings will conflict and stop it from launching properly.
  frontend:
    build: ./frontend
    environment:
      HWF_DB_URL: "PLACEHOLDER"
    ports:
      - 3000:3000

  server:
      build: ./server
      ports:
        - 3001:3001
        - 9000:9000
        - 27071:27071
      environment:
        HWF_DB_URL: "mongodb://localhost:27017/test"
      # volumes:
      #   - storage:data/db

  database:
    build: ./database
    ports:
      - 27017:27017

  # daemon:
  #   build: ./daemon
  #   ports:
  #     - 9000:9000 
  #   environment:
  #     HWF_SERVER_URL: "PLACEHOLDER"

# volumes:
#   storage: