// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package schema

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type GetResults struct {
	_tab flatbuffers.Table
}

func GetRootAsGetResults(buf []byte, offset flatbuffers.UOffsetT) *GetResults {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &GetResults{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsGetResults(buf []byte, offset flatbuffers.UOffsetT) *GetResults {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &GetResults{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *GetResults) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *GetResults) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *GetResults) IdList(j int) int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetInt32(a + flatbuffers.UOffsetT(j*4))
	}
	return 0
}

func (rcv *GetResults) IdListLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *GetResults) MutateIdList(j int, n int32) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateInt32(a+flatbuffers.UOffsetT(j*4), n)
	}
	return false
}

func GetResultsStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func GetResultsAddIdList(builder *flatbuffers.Builder, idList flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(idList), 0)
}
func GetResultsStartIdListVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func GetResultsEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
