// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package schema

import "strconv"

type MessageBody byte

const (
	MessageBodyNONE            MessageBody = 0
	MessageBodyTask            MessageBody = 1
	MessageBodyGetResult       MessageBody = 2
	MessageBodyGetHardwarePool MessageBody = 3
	MessageBodyFile            MessageBody = 4
	MessageBodyResult          MessageBody = 5
	MessageBodyResultList      MessageBody = 6
	MessageBodyHardware        MessageBody = 7
)

var EnumNamesMessageBody = map[MessageBody]string{
	MessageBodyNONE:            "NONE",
	MessageBodyTask:            "Task",
	MessageBodyGetResult:       "GetResult",
	MessageBodyGetHardwarePool: "GetHardwarePool",
	MessageBodyFile:            "File",
	MessageBodyResult:          "Result",
	MessageBodyResultList:      "ResultList",
	MessageBodyHardware:        "Hardware",
}

var EnumValuesMessageBody = map[string]MessageBody{
	"NONE":            MessageBodyNONE,
	"Task":            MessageBodyTask,
	"GetResult":       MessageBodyGetResult,
	"GetHardwarePool": MessageBodyGetHardwarePool,
	"File":            MessageBodyFile,
	"Result":          MessageBodyResult,
	"ResultList":      MessageBodyResultList,
	"Hardware":        MessageBodyHardware,
}

func (v MessageBody) String() string {
	if s, ok := EnumNamesMessageBody[v]; ok {
		return s
	}
	return "MessageBody(" + strconv.FormatInt(int64(v), 10) + ")"
}
