// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package schema

type MessageBody = byte
const (
	MessageBodyNONE MessageBody = 0
	MessageBodyTask MessageBody = 1
	MessageBodyGetResult MessageBody = 2
	MessageBodyGetHardwarePool MessageBody = 3
	MessageBodyFile MessageBody = 4
)

var EnumNamesMessageBody = map[MessageBody]string{
	MessageBodyNONE:"NONE",
	MessageBodyTask:"Task",
	MessageBodyGetResult:"GetResult",
	MessageBodyGetHardwarePool:"GetHardwarePool",
	MessageBodyFile:"File",
}

