// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package schema

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ResultList struct {
	_tab flatbuffers.Table
}

func GetRootAsResultList(buf []byte, offset flatbuffers.UOffsetT) *ResultList {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ResultList{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsResultList(buf []byte, offset flatbuffers.UOffsetT) *ResultList {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ResultList{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *ResultList) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ResultList) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ResultList) Tasks(obj *Result, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *ResultList) TasksLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func ResultListStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func ResultListAddTasks(builder *flatbuffers.Builder, tasks flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(tasks), 0)
}
func ResultListStartTasksVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func ResultListEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
