#This is pretty much a placeholder until after the db files have been moved to this folder, then you can update it to properly launch the db.
FROM mongo:4.0-xenial

COPY . ./database
WORKDIR /database

CMD mongod 