# automatically generated by the FlatBuffers compiler, do not modify

# namespace: schema

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class GetHardwarePool(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = GetHardwarePool()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsGetHardwarePool(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # GetHardwarePool
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # GetHardwarePool
    def Hardware(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.String(a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return ""

    # GetHardwarePool
    def HardwareLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # GetHardwarePool
    def HardwareIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def Start(builder): builder.StartObject(1)
def GetHardwarePoolStart(builder):
    """This method is deprecated. Please switch to Start."""
    return Start(builder)
def AddHardware(builder, hardware): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(hardware), 0)
def GetHardwarePoolAddHardware(builder, hardware):
    """This method is deprecated. Please switch to AddHardware."""
    return AddHardware(builder, hardware)
def StartHardwareVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def GetHardwarePoolStartHardwareVector(builder, numElems):
    """This method is deprecated. Please switch to Start."""
    return StartHardwareVector(builder, numElems)
def End(builder): return builder.EndObject()
def GetHardwarePoolEnd(builder):
    """This method is deprecated. Please switch to End."""
    return End(builder)