# automatically generated by the FlatBuffers compiler, do not modify

# namespace: schema

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class GetHardwarePool(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsGetHardwarePool(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = GetHardwarePool()
        x.Init(buf, n + offset)
        return x

    # GetHardwarePool
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # GetHardwarePool
    def Hardware(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.String(a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return ""

    # GetHardwarePool
    def HardwareLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # GetHardwarePool
    def HardwareIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def GetHardwarePoolStart(builder): builder.StartObject(1)
def GetHardwarePoolAddHardware(builder, hardware): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(hardware), 0)
def GetHardwarePoolStartHardwareVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def GetHardwarePoolEnd(builder): return builder.EndObject()
