# automatically generated by the FlatBuffers compiler, do not modify

# namespace: schema

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Hardware(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Hardware()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsHardware(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Hardware
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Hardware
    def Cpu(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Hardware
    def Gpu(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Hardware
    def Os(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Hardware
    def Ram(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def Start(builder): builder.StartObject(4)
def HardwareStart(builder):
    """This method is deprecated. Please switch to Start."""
    return Start(builder)
def AddCpu(builder, cpu): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(cpu), 0)
def HardwareAddCpu(builder, cpu):
    """This method is deprecated. Please switch to AddCpu."""
    return AddCpu(builder, cpu)
def AddGpu(builder, gpu): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(gpu), 0)
def HardwareAddGpu(builder, gpu):
    """This method is deprecated. Please switch to AddGpu."""
    return AddGpu(builder, gpu)
def AddOs(builder, os): builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(os), 0)
def HardwareAddOs(builder, os):
    """This method is deprecated. Please switch to AddOs."""
    return AddOs(builder, os)
def AddRam(builder, ram): builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(ram), 0)
def HardwareAddRam(builder, ram):
    """This method is deprecated. Please switch to AddRam."""
    return AddRam(builder, ram)
def End(builder): return builder.EndObject()
def HardwareEnd(builder):
    """This method is deprecated. Please switch to End."""
    return End(builder)