# automatically generated by the FlatBuffers compiler, do not modify

# namespace: schema

class MessageBody(object):
    NONE = 0
    Task = 1
    GetResult = 2
    GetHardwarePool = 3
    File = 4

