# automatically generated by the FlatBuffers compiler, do not modify

# namespace: schema

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Stage(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Stage()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsStage(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Stage
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Stage
    def Name(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Stage
    def Data(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # Stage
    def DataAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int8Flags, o)
        return 0

    # Stage
    def DataLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Stage
    def DataIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

    # Stage
    def CmdList(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.String(a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return ""

    # Stage
    def CmdListLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Stage
    def CmdListIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

    # Stage
    def TrackTime(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # Stage
    def TrackRam(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # Stage
    def TrackCpu(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # Stage
    def TrackGpu(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # Stage
    def Comment(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def Start(builder): builder.StartObject(8)
def StageStart(builder):
    """This method is deprecated. Please switch to Start."""
    return Start(builder)
def AddName(builder, name): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(name), 0)
def StageAddName(builder, name):
    """This method is deprecated. Please switch to AddName."""
    return AddName(builder, name)
def AddData(builder, data): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(data), 0)
def StageAddData(builder, data):
    """This method is deprecated. Please switch to AddData."""
    return AddData(builder, data)
def StartDataVector(builder, numElems): return builder.StartVector(1, numElems, 1)
def StageStartDataVector(builder, numElems):
    """This method is deprecated. Please switch to Start."""
    return StartDataVector(builder, numElems)
def AddCmdList(builder, cmdList): builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(cmdList), 0)
def StageAddCmdList(builder, cmdList):
    """This method is deprecated. Please switch to AddCmdList."""
    return AddCmdList(builder, cmdList)
def StartCmdListVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def StageStartCmdListVector(builder, numElems):
    """This method is deprecated. Please switch to Start."""
    return StartCmdListVector(builder, numElems)
def AddTrackTime(builder, trackTime): builder.PrependBoolSlot(3, trackTime, 0)
def StageAddTrackTime(builder, trackTime):
    """This method is deprecated. Please switch to AddTrackTime."""
    return AddTrackTime(builder, trackTime)
def AddTrackRam(builder, trackRam): builder.PrependBoolSlot(4, trackRam, 0)
def StageAddTrackRam(builder, trackRam):
    """This method is deprecated. Please switch to AddTrackRam."""
    return AddTrackRam(builder, trackRam)
def AddTrackCpu(builder, trackCpu): builder.PrependBoolSlot(5, trackCpu, 0)
def StageAddTrackCpu(builder, trackCpu):
    """This method is deprecated. Please switch to AddTrackCpu."""
    return AddTrackCpu(builder, trackCpu)
def AddTrackGpu(builder, trackGpu): builder.PrependBoolSlot(6, trackGpu, 0)
def StageAddTrackGpu(builder, trackGpu):
    """This method is deprecated. Please switch to AddTrackGpu."""
    return AddTrackGpu(builder, trackGpu)
def AddComment(builder, comment): builder.PrependUOffsetTRelativeSlot(7, flatbuffers.number_types.UOffsetTFlags.py_type(comment), 0)
def StageAddComment(builder, comment):
    """This method is deprecated. Please switch to AddComment."""
    return AddComment(builder, comment)
def End(builder): return builder.EndObject()
def StageEnd(builder):
    """This method is deprecated. Please switch to End."""
    return End(builder)