# automatically generated by the FlatBuffers compiler, do not modify

# namespace: schema

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class StageResult(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = StageResult()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsStageResult(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # StageResult
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # StageResult
    def Cmd(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from schema.CommandResult import CommandResult
            obj = CommandResult()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # StageResult
    def CmdLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # StageResult
    def CmdIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

    # StageResult
    def Name(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def Start(builder): builder.StartObject(2)
def StageResultStart(builder):
    """This method is deprecated. Please switch to Start."""
    return Start(builder)
def AddCmd(builder, cmd): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(cmd), 0)
def StageResultAddCmd(builder, cmd):
    """This method is deprecated. Please switch to AddCmd."""
    return AddCmd(builder, cmd)
def StartCmdVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def StageResultStartCmdVector(builder, numElems):
    """This method is deprecated. Please switch to Start."""
    return StartCmdVector(builder, numElems)
def AddName(builder, name): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(name), 0)
def StageResultAddName(builder, name):
    """This method is deprecated. Please switch to AddName."""
    return AddName(builder, name)
def End(builder): return builder.EndObject()
def StageResultEnd(builder):
    """This method is deprecated. Please switch to End."""
    return End(builder)