// automatically generated by the FlatBuffers compiler, do not modify

import { flatbuffers } from "./flatbuffers"
/**
 * @constructor
 */
export namespace schema{
export class Message {
  bb: flatbuffers.ByteBuffer|null = null;

  bb_pos:number = 0;
/**
 * @param number i
 * @param flatbuffers.ByteBuffer bb
 * @returns Message
 */
__init(i:number, bb:flatbuffers.ByteBuffer):Message {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param Message= obj
 * @returns Message
 */
static getRootAsMessage(bb:flatbuffers.ByteBuffer, obj?:Message):Message {
  return (obj || new Message).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns number
 */
type():number {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
};

/**
 * @param schema.Task= obj
 * @returns schema.Task|null
 */
task(obj?:schema.Task):schema.Task|null {
  var offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new schema.Task).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
};

/**
 * @param schema.GetResult= obj
 * @returns schema.GetResult|null
 */
getResult(obj?:schema.GetResult):schema.GetResult|null {
  var offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? (obj || new schema.GetResult).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
};

/**
 * @param schema.GetHardwarePool= obj
 * @returns schema.GetHardwarePool|null
 */
getHardwarePool(obj?:schema.GetHardwarePool):schema.GetHardwarePool|null {
  var offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? (obj || new schema.GetHardwarePool).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
};

/**
 * @param flatbuffers.Builder builder
 */
static startMessage(builder:flatbuffers.Builder) {
  builder.startObject(4);
};

/**
 * @param flatbuffers.Builder builder
 * @param number type
 */
static addType(builder:flatbuffers.Builder, type:number) {
  builder.addFieldInt32(0, type, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset taskOffset
 */
static addTask(builder:flatbuffers.Builder, taskOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, taskOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset getResultOffset
 */
static addGetResult(builder:flatbuffers.Builder, getResultOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, getResultOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset getHardwarePoolOffset
 */
static addGetHardwarePool(builder:flatbuffers.Builder, getHardwarePoolOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, getHardwarePoolOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @returns flatbuffers.Offset
 */
static endMessage(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset offset
 */
static finishMessageBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset);
};

static createMessage(builder:flatbuffers.Builder, type:number, taskOffset:flatbuffers.Offset, getResultOffset:flatbuffers.Offset, getHardwarePoolOffset:flatbuffers.Offset):flatbuffers.Offset {
  Message.startMessage(builder);
  Message.addType(builder, type);
  Message.addTask(builder, taskOffset);
  Message.addGetResult(builder, getResultOffset);
  Message.addGetHardwarePool(builder, getHardwarePoolOffset);
  return Message.endMessage(builder);
}
}
}
/**
 * @constructor
 */
export namespace schema{
export class Stage {
  bb: flatbuffers.ByteBuffer|null = null;

  bb_pos:number = 0;
/**
 * @param number i
 * @param flatbuffers.ByteBuffer bb
 * @returns Stage
 */
__init(i:number, bb:flatbuffers.ByteBuffer):Stage {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param Stage= obj
 * @returns Stage
 */
static getRootAsStage(bb:flatbuffers.ByteBuffer, obj?:Stage):Stage {
  return (obj || new Stage).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param flatbuffers.Encoding= optionalEncoding
 * @returns string|Uint8Array|null
 */
name():string|null
name(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
name(optionalEncoding?:any):string|Uint8Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param number index
 * @returns number
 */
data(index: number):number|null {
  var offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readInt8(this.bb!.__vector(this.bb_pos + offset) + index) : 0;
};

/**
 * @returns number
 */
dataLength():number {
  var offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @returns Int8Array
 */
dataArray():Int8Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? new Int8Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
};

/**
 * @param number index
 * @param flatbuffers.Encoding= optionalEncoding
 * @returns string|Uint8Array
 */
cmdList(index: number):string
cmdList(index: number,optionalEncoding:flatbuffers.Encoding):string|Uint8Array
cmdList(index: number,optionalEncoding?:any):string|Uint8Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__string(this.bb!.__vector(this.bb_pos + offset) + index * 4, optionalEncoding) : null;
};

/**
 * @returns number
 */
cmdListLength():number {
  var offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @returns boolean
 */
trackTime():boolean {
  var offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : true;
};

/**
 * @returns boolean
 */
trackRam():boolean {
  var offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
};

/**
 * @returns boolean
 */
trackCpu():boolean {
  var offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
};

/**
 * @returns boolean
 */
trackGpu():boolean {
  var offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
};

/**
 * @param flatbuffers.Encoding= optionalEncoding
 * @returns string|Uint8Array|null
 */
comment():string|null
comment(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
comment(optionalEncoding?:any):string|Uint8Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 18);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param flatbuffers.Builder builder
 */
static startStage(builder:flatbuffers.Builder) {
  builder.startObject(8);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset nameOffset
 */
static addName(builder:flatbuffers.Builder, nameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, nameOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset dataOffset
 */
static addData(builder:flatbuffers.Builder, dataOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, dataOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param Array.<number> data
 * @returns flatbuffers.Offset
 */
static createDataVector(builder:flatbuffers.Builder, data:number[] | Uint8Array):flatbuffers.Offset {
  builder.startVector(1, data.length, 1);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addInt8(data[i]);
  }
  return builder.endVector();
};

/**
 * @param flatbuffers.Builder builder
 * @param number numElems
 */
static startDataVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(1, numElems, 1);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset cmdListOffset
 */
static addCmdList(builder:flatbuffers.Builder, cmdListOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, cmdListOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param Array.<flatbuffers.Offset> data
 * @returns flatbuffers.Offset
 */
static createCmdListVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]);
  }
  return builder.endVector();
};

/**
 * @param flatbuffers.Builder builder
 * @param number numElems
 */
static startCmdListVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
};

/**
 * @param flatbuffers.Builder builder
 * @param boolean trackTime
 */
static addTrackTime(builder:flatbuffers.Builder, trackTime:boolean) {
  builder.addFieldInt8(3, +trackTime, +true);
};

/**
 * @param flatbuffers.Builder builder
 * @param boolean trackRam
 */
static addTrackRam(builder:flatbuffers.Builder, trackRam:boolean) {
  builder.addFieldInt8(4, +trackRam, +false);
};

/**
 * @param flatbuffers.Builder builder
 * @param boolean trackCpu
 */
static addTrackCpu(builder:flatbuffers.Builder, trackCpu:boolean) {
  builder.addFieldInt8(5, +trackCpu, +false);
};

/**
 * @param flatbuffers.Builder builder
 * @param boolean trackGpu
 */
static addTrackGpu(builder:flatbuffers.Builder, trackGpu:boolean) {
  builder.addFieldInt8(6, +trackGpu, +false);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset commentOffset
 */
static addComment(builder:flatbuffers.Builder, commentOffset:flatbuffers.Offset) {
  builder.addFieldOffset(7, commentOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @returns flatbuffers.Offset
 */
static endStage(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

static createStage(builder:flatbuffers.Builder, nameOffset:flatbuffers.Offset, dataOffset:flatbuffers.Offset, cmdListOffset:flatbuffers.Offset, trackTime:boolean, trackRam:boolean, trackCpu:boolean, trackGpu:boolean, commentOffset:flatbuffers.Offset):flatbuffers.Offset {
  Stage.startStage(builder);
  Stage.addName(builder, nameOffset);
  Stage.addData(builder, dataOffset);
  Stage.addCmdList(builder, cmdListOffset);
  Stage.addTrackTime(builder, trackTime);
  Stage.addTrackRam(builder, trackRam);
  Stage.addTrackCpu(builder, trackCpu);
  Stage.addTrackGpu(builder, trackGpu);
  Stage.addComment(builder, commentOffset);
  return Stage.endStage(builder);
}
}
}
/**
 * @constructor
 */
export namespace schema{
export class Task {
  bb: flatbuffers.ByteBuffer|null = null;

  bb_pos:number = 0;
/**
 * @param number i
 * @param flatbuffers.ByteBuffer bb
 * @returns Task
 */
__init(i:number, bb:flatbuffers.ByteBuffer):Task {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param Task= obj
 * @returns Task
 */
static getRootAsTask(bb:flatbuffers.ByteBuffer, obj?:Task):Task {
  return (obj || new Task).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param number index
 * @param schema.Stage= obj
 * @returns schema.Stage
 */
stages(index: number, obj?:schema.Stage):schema.Stage|null {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new schema.Stage).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
};

/**
 * @returns number
 */
stagesLength():number {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @param number index
 * @param flatbuffers.Encoding= optionalEncoding
 * @returns string|Uint8Array
 */
artifacts(index: number):string
artifacts(index: number,optionalEncoding:flatbuffers.Encoding):string|Uint8Array
artifacts(index: number,optionalEncoding?:any):string|Uint8Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb!.__vector(this.bb_pos + offset) + index * 4, optionalEncoding) : null;
};

/**
 * @returns number
 */
artifactsLength():number {
  var offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @param flatbuffers.Builder builder
 */
static startTask(builder:flatbuffers.Builder) {
  builder.startObject(2);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset stagesOffset
 */
static addStages(builder:flatbuffers.Builder, stagesOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, stagesOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param Array.<flatbuffers.Offset> data
 * @returns flatbuffers.Offset
 */
static createStagesVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]);
  }
  return builder.endVector();
};

/**
 * @param flatbuffers.Builder builder
 * @param number numElems
 */
static startStagesVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset artifactsOffset
 */
static addArtifacts(builder:flatbuffers.Builder, artifactsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, artifactsOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param Array.<flatbuffers.Offset> data
 * @returns flatbuffers.Offset
 */
static createArtifactsVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]);
  }
  return builder.endVector();
};

/**
 * @param flatbuffers.Builder builder
 * @param number numElems
 */
static startArtifactsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
};

/**
 * @param flatbuffers.Builder builder
 * @returns flatbuffers.Offset
 */
static endTask(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

static createTask(builder:flatbuffers.Builder, stagesOffset:flatbuffers.Offset, artifactsOffset:flatbuffers.Offset):flatbuffers.Offset {
  Task.startTask(builder);
  Task.addStages(builder, stagesOffset);
  Task.addArtifacts(builder, artifactsOffset);
  return Task.endTask(builder);
}
}
}
/**
 * @constructor
 */
export namespace schema{
export class GetResult {
  bb: flatbuffers.ByteBuffer|null = null;

  bb_pos:number = 0;
/**
 * @param number i
 * @param flatbuffers.ByteBuffer bb
 * @returns GetResult
 */
__init(i:number, bb:flatbuffers.ByteBuffer):GetResult {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param GetResult= obj
 * @returns GetResult
 */
static getRootAsGetResult(bb:flatbuffers.ByteBuffer, obj?:GetResult):GetResult {
  return (obj || new GetResult).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param number index
 * @param flatbuffers.Encoding= optionalEncoding
 * @returns string|Uint8Array
 */
idList(index: number):string
idList(index: number,optionalEncoding:flatbuffers.Encoding):string|Uint8Array
idList(index: number,optionalEncoding?:any):string|Uint8Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb!.__vector(this.bb_pos + offset) + index * 4, optionalEncoding) : null;
};

/**
 * @returns number
 */
idListLength():number {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @param flatbuffers.Builder builder
 */
static startGetResult(builder:flatbuffers.Builder) {
  builder.startObject(1);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset idListOffset
 */
static addIdList(builder:flatbuffers.Builder, idListOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, idListOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param Array.<flatbuffers.Offset> data
 * @returns flatbuffers.Offset
 */
static createIdListVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]);
  }
  return builder.endVector();
};

/**
 * @param flatbuffers.Builder builder
 * @param number numElems
 */
static startIdListVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
};

/**
 * @param flatbuffers.Builder builder
 * @returns flatbuffers.Offset
 */
static endGetResult(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

static createGetResult(builder:flatbuffers.Builder, idListOffset:flatbuffers.Offset):flatbuffers.Offset {
  GetResult.startGetResult(builder);
  GetResult.addIdList(builder, idListOffset);
  return GetResult.endGetResult(builder);
}
}
}
/**
 * @constructor
 */
export namespace schema{
export class GetHardwarePool {
  bb: flatbuffers.ByteBuffer|null = null;

  bb_pos:number = 0;
/**
 * @param number i
 * @param flatbuffers.ByteBuffer bb
 * @returns GetHardwarePool
 */
__init(i:number, bb:flatbuffers.ByteBuffer):GetHardwarePool {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param GetHardwarePool= obj
 * @returns GetHardwarePool
 */
static getRootAsGetHardwarePool(bb:flatbuffers.ByteBuffer, obj?:GetHardwarePool):GetHardwarePool {
  return (obj || new GetHardwarePool).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param number index
 * @param flatbuffers.Encoding= optionalEncoding
 * @returns string|Uint8Array
 */
hardware(index: number):string
hardware(index: number,optionalEncoding:flatbuffers.Encoding):string|Uint8Array
hardware(index: number,optionalEncoding?:any):string|Uint8Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb!.__vector(this.bb_pos + offset) + index * 4, optionalEncoding) : null;
};

/**
 * @returns number
 */
hardwareLength():number {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @param flatbuffers.Builder builder
 */
static startGetHardwarePool(builder:flatbuffers.Builder) {
  builder.startObject(1);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset hardwareOffset
 */
static addHardware(builder:flatbuffers.Builder, hardwareOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, hardwareOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param Array.<flatbuffers.Offset> data
 * @returns flatbuffers.Offset
 */
static createHardwareVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]);
  }
  return builder.endVector();
};

/**
 * @param flatbuffers.Builder builder
 * @param number numElems
 */
static startHardwareVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
};

/**
 * @param flatbuffers.Builder builder
 * @returns flatbuffers.Offset
 */
static endGetHardwarePool(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

static createGetHardwarePool(builder:flatbuffers.Builder, hardwareOffset:flatbuffers.Offset):flatbuffers.Offset {
  GetHardwarePool.startGetHardwarePool(builder);
  GetHardwarePool.addHardware(builder, hardwareOffset);
  return GetHardwarePool.endGetHardwarePool(builder);
}
}
}
