// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';
/**
 * @enum {number}
 */
export namespace schema{
export enum MessageBody{
  NONE= 0,
  Task= 1,
  GetResult= 2,
  GetHardwarePool= 3,
  File= 4,
  Result= 5,
  ResultList= 6,
  Hardware= 7
};

export function unionToMessageBody(
  type: MessageBody,
  accessor: (obj:schema.File|schema.GetHardwarePool|schema.GetResult|schema.Hardware|schema.Result|schema.ResultList|schema.Task) => schema.File|schema.GetHardwarePool|schema.GetResult|schema.Hardware|schema.Result|schema.ResultList|schema.Task|null
): schema.File|schema.GetHardwarePool|schema.GetResult|schema.Hardware|schema.Result|schema.ResultList|schema.Task|null {
  switch(schema.MessageBody[type]) {
    case 'NONE': return null; 
    case 'Task': return accessor(new schema.Task())! as schema.Task;
    case 'GetResult': return accessor(new schema.GetResult())! as schema.GetResult;
    case 'GetHardwarePool': return accessor(new schema.GetHardwarePool())! as schema.GetHardwarePool;
    case 'File': return accessor(new schema.File())! as schema.File;
    case 'Result': return accessor(new schema.Result())! as schema.Result;
    case 'ResultList': return accessor(new schema.ResultList())! as schema.ResultList;
    case 'Hardware': return accessor(new schema.Hardware())! as schema.Hardware;
    default: return null;
  }
}

export function unionListToMessageBody(
  type: MessageBody, 
  accessor: (index: number, obj:schema.File|schema.GetHardwarePool|schema.GetResult|schema.Hardware|schema.Result|schema.ResultList|schema.Task) => schema.File|schema.GetHardwarePool|schema.GetResult|schema.Hardware|schema.Result|schema.ResultList|schema.Task|null, 
  index: number
): schema.File|schema.GetHardwarePool|schema.GetResult|schema.Hardware|schema.Result|schema.ResultList|schema.Task|null {
  switch(schema.MessageBody[type]) {
    case 'NONE': return null; 
    case 'Task': return accessor(index, new schema.Task())! as schema.Task;
    case 'GetResult': return accessor(index, new schema.GetResult())! as schema.GetResult;
    case 'GetHardwarePool': return accessor(index, new schema.GetHardwarePool())! as schema.GetHardwarePool;
    case 'File': return accessor(index, new schema.File())! as schema.File;
    case 'Result': return accessor(index, new schema.Result())! as schema.Result;
    case 'ResultList': return accessor(index, new schema.ResultList())! as schema.ResultList;
    case 'Hardware': return accessor(index, new schema.Hardware())! as schema.Hardware;
    default: return null;
  }
}
}

/**
 * @constructor
 */
export namespace schema{
export class Message {
  bb: flatbuffers.ByteBuffer|null = null;

  bb_pos:number = 0;
/**
 * @param number i
 * @param flatbuffers.ByteBuffer bb
 * @returns Message
 */
__init(i:number, bb:flatbuffers.ByteBuffer):Message {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param Message= obj
 * @returns Message
 */
static getRootAsMessage(bb:flatbuffers.ByteBuffer, obj?:Message):Message {
  return (obj || new Message()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param Message= obj
 * @returns Message
 */
static getSizePrefixedRootAsMessage(bb:flatbuffers.ByteBuffer, obj?:Message):Message {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Message()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns number
 */
type():number {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
};

/**
 * @returns schema.MessageBody
 */
bodyType():schema.MessageBody {
  var offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? /**  */ (this.bb!.readUint8(this.bb_pos + offset)) : schema.MessageBody.NONE;
};

/**
 * @param flatbuffers.Table obj
 * @returns ?flatbuffers.Table
 */
body<T extends flatbuffers.Table>(obj:T):T|null|flatbuffers.Table {
  var offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__union(obj, this.bb_pos + offset) : null;
};

/**
 * @param flatbuffers.Builder builder
 */
static startMessage(builder:flatbuffers.Builder) {
  builder.startObject(3);
};

/**
 * @param flatbuffers.Builder builder
 * @param number type
 */
static addType(builder:flatbuffers.Builder, type:number) {
  builder.addFieldInt32(0, type, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param schema.MessageBody bodyType
 */
static addBodyType(builder:flatbuffers.Builder, bodyType:schema.MessageBody) {
  builder.addFieldInt8(1, bodyType, schema.MessageBody.NONE);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset bodyOffset
 */
static addBody(builder:flatbuffers.Builder, bodyOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, bodyOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @returns flatbuffers.Offset
 */
static endMessage(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset offset
 */
static finishMessageBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset offset
 */
static finishSizePrefixedMessageBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset, undefined, true);
};

static createMessage(builder:flatbuffers.Builder, type:number, bodyType:schema.MessageBody, bodyOffset:flatbuffers.Offset):flatbuffers.Offset {
  Message.startMessage(builder);
  Message.addType(builder, type);
  Message.addBodyType(builder, bodyType);
  Message.addBody(builder, bodyOffset);
  return Message.endMessage(builder);
}
}
}
/**
 * @constructor
 */
export namespace schema{
export class Stage {
  bb: flatbuffers.ByteBuffer|null = null;

  bb_pos:number = 0;
/**
 * @param number i
 * @param flatbuffers.ByteBuffer bb
 * @returns Stage
 */
__init(i:number, bb:flatbuffers.ByteBuffer):Stage {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param Stage= obj
 * @returns Stage
 */
static getRootAsStage(bb:flatbuffers.ByteBuffer, obj?:Stage):Stage {
  return (obj || new Stage()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param Stage= obj
 * @returns Stage
 */
static getSizePrefixedRootAsStage(bb:flatbuffers.ByteBuffer, obj?:Stage):Stage {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Stage()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param flatbuffers.Encoding= optionalEncoding
 * @returns string|Uint8Array|null
 */
name():string|null
name(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
name(optionalEncoding?:any):string|Uint8Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param number index
 * @param schema.Data= obj
 * @returns schema.Data
 */
data(index: number, obj?:schema.Data):schema.Data|null {
  var offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new schema.Data()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
};

/**
 * @returns number
 */
dataLength():number {
  var offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @param number index
 * @param flatbuffers.Encoding= optionalEncoding
 * @returns string|Uint8Array
 */
cmdList(index: number):string
cmdList(index: number,optionalEncoding:flatbuffers.Encoding):string|Uint8Array
cmdList(index: number,optionalEncoding?:any):string|Uint8Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__string(this.bb!.__vector(this.bb_pos + offset) + index * 4, optionalEncoding) : null;
};

/**
 * @returns number
 */
cmdListLength():number {
  var offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @returns boolean
 */
trackTime():boolean {
  var offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : true;
};

/**
 * @returns boolean
 */
trackRam():boolean {
  var offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
};

/**
 * @returns boolean
 */
trackCpu():boolean {
  var offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
};

/**
 * @returns boolean
 */
trackGpu():boolean {
  var offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
};

/**
 * @param flatbuffers.Encoding= optionalEncoding
 * @returns string|Uint8Array|null
 */
comment():string|null
comment(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
comment(optionalEncoding?:any):string|Uint8Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 18);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param flatbuffers.Builder builder
 */
static startStage(builder:flatbuffers.Builder) {
  builder.startObject(8);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset nameOffset
 */
static addName(builder:flatbuffers.Builder, nameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, nameOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset dataOffset
 */
static addData(builder:flatbuffers.Builder, dataOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, dataOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param Array.<flatbuffers.Offset> data
 * @returns flatbuffers.Offset
 */
static createDataVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]);
  }
  return builder.endVector();
};

/**
 * @param flatbuffers.Builder builder
 * @param number numElems
 */
static startDataVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset cmdListOffset
 */
static addCmdList(builder:flatbuffers.Builder, cmdListOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, cmdListOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param Array.<flatbuffers.Offset> data
 * @returns flatbuffers.Offset
 */
static createCmdListVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]);
  }
  return builder.endVector();
};

/**
 * @param flatbuffers.Builder builder
 * @param number numElems
 */
static startCmdListVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
};

/**
 * @param flatbuffers.Builder builder
 * @param boolean trackTime
 */
static addTrackTime(builder:flatbuffers.Builder, trackTime:boolean) {
  builder.addFieldInt8(3, +trackTime, +true);
};

/**
 * @param flatbuffers.Builder builder
 * @param boolean trackRam
 */
static addTrackRam(builder:flatbuffers.Builder, trackRam:boolean) {
  builder.addFieldInt8(4, +trackRam, +false);
};

/**
 * @param flatbuffers.Builder builder
 * @param boolean trackCpu
 */
static addTrackCpu(builder:flatbuffers.Builder, trackCpu:boolean) {
  builder.addFieldInt8(5, +trackCpu, +false);
};

/**
 * @param flatbuffers.Builder builder
 * @param boolean trackGpu
 */
static addTrackGpu(builder:flatbuffers.Builder, trackGpu:boolean) {
  builder.addFieldInt8(6, +trackGpu, +false);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset commentOffset
 */
static addComment(builder:flatbuffers.Builder, commentOffset:flatbuffers.Offset) {
  builder.addFieldOffset(7, commentOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @returns flatbuffers.Offset
 */
static endStage(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

static createStage(builder:flatbuffers.Builder, nameOffset:flatbuffers.Offset, dataOffset:flatbuffers.Offset, cmdListOffset:flatbuffers.Offset, trackTime:boolean, trackRam:boolean, trackCpu:boolean, trackGpu:boolean, commentOffset:flatbuffers.Offset):flatbuffers.Offset {
  Stage.startStage(builder);
  Stage.addName(builder, nameOffset);
  Stage.addData(builder, dataOffset);
  Stage.addCmdList(builder, cmdListOffset);
  Stage.addTrackTime(builder, trackTime);
  Stage.addTrackRam(builder, trackRam);
  Stage.addTrackCpu(builder, trackCpu);
  Stage.addTrackGpu(builder, trackGpu);
  Stage.addComment(builder, commentOffset);
  return Stage.endStage(builder);
}
}
}
/**
 * @constructor
 */
export namespace schema{
export class Data {
  bb: flatbuffers.ByteBuffer|null = null;

  bb_pos:number = 0;
/**
 * @param number i
 * @param flatbuffers.ByteBuffer bb
 * @returns Data
 */
__init(i:number, bb:flatbuffers.ByteBuffer):Data {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param Data= obj
 * @returns Data
 */
static getRootAsData(bb:flatbuffers.ByteBuffer, obj?:Data):Data {
  return (obj || new Data()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param Data= obj
 * @returns Data
 */
static getSizePrefixedRootAsData(bb:flatbuffers.ByteBuffer, obj?:Data):Data {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Data()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param flatbuffers.Encoding= optionalEncoding
 * @returns string|Uint8Array|null
 */
path():string|null
path(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
path(optionalEncoding?:any):string|Uint8Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param flatbuffers.Encoding= optionalEncoding
 * @returns string|Uint8Array|null
 */
filename():string|null
filename(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
filename(optionalEncoding?:any):string|Uint8Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param flatbuffers.Builder builder
 */
static startData(builder:flatbuffers.Builder) {
  builder.startObject(2);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset pathOffset
 */
static addPath(builder:flatbuffers.Builder, pathOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, pathOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset filenameOffset
 */
static addFilename(builder:flatbuffers.Builder, filenameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, filenameOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @returns flatbuffers.Offset
 */
static endData(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

static createData(builder:flatbuffers.Builder, pathOffset:flatbuffers.Offset, filenameOffset:flatbuffers.Offset):flatbuffers.Offset {
  Data.startData(builder);
  Data.addPath(builder, pathOffset);
  Data.addFilename(builder, filenameOffset);
  return Data.endData(builder);
}
}
}
/**
 * @constructor
 */
export namespace schema{
export class Task {
  bb: flatbuffers.ByteBuffer|null = null;

  bb_pos:number = 0;
/**
 * @param number i
 * @param flatbuffers.ByteBuffer bb
 * @returns Task
 */
__init(i:number, bb:flatbuffers.ByteBuffer):Task {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param Task= obj
 * @returns Task
 */
static getRootAsTask(bb:flatbuffers.ByteBuffer, obj?:Task):Task {
  return (obj || new Task()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param Task= obj
 * @returns Task
 */
static getSizePrefixedRootAsTask(bb:flatbuffers.ByteBuffer, obj?:Task):Task {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Task()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param schema.Hardware= obj
 * @returns schema.Hardware|null
 */
hardware(obj?:schema.Hardware):schema.Hardware|null {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new schema.Hardware()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
};

/**
 * @param number index
 * @param schema.Stage= obj
 * @returns schema.Stage
 */
stages(index: number, obj?:schema.Stage):schema.Stage|null {
  var offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new schema.Stage()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
};

/**
 * @returns number
 */
stagesLength():number {
  var offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @param number index
 * @param flatbuffers.Encoding= optionalEncoding
 * @returns string|Uint8Array
 */
artifacts(index: number):string
artifacts(index: number,optionalEncoding:flatbuffers.Encoding):string|Uint8Array
artifacts(index: number,optionalEncoding?:any):string|Uint8Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__string(this.bb!.__vector(this.bb_pos + offset) + index * 4, optionalEncoding) : null;
};

/**
 * @returns number
 */
artifactsLength():number {
  var offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @param flatbuffers.Builder builder
 */
static startTask(builder:flatbuffers.Builder) {
  builder.startObject(3);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset hardwareOffset
 */
static addHardware(builder:flatbuffers.Builder, hardwareOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, hardwareOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset stagesOffset
 */
static addStages(builder:flatbuffers.Builder, stagesOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, stagesOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param Array.<flatbuffers.Offset> data
 * @returns flatbuffers.Offset
 */
static createStagesVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]);
  }
  return builder.endVector();
};

/**
 * @param flatbuffers.Builder builder
 * @param number numElems
 */
static startStagesVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset artifactsOffset
 */
static addArtifacts(builder:flatbuffers.Builder, artifactsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, artifactsOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param Array.<flatbuffers.Offset> data
 * @returns flatbuffers.Offset
 */
static createArtifactsVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]);
  }
  return builder.endVector();
};

/**
 * @param flatbuffers.Builder builder
 * @param number numElems
 */
static startArtifactsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
};

/**
 * @param flatbuffers.Builder builder
 * @returns flatbuffers.Offset
 */
static endTask(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

static createTask(builder:flatbuffers.Builder, hardwareOffset:flatbuffers.Offset, stagesOffset:flatbuffers.Offset, artifactsOffset:flatbuffers.Offset):flatbuffers.Offset {
  Task.startTask(builder);
  Task.addHardware(builder, hardwareOffset);
  Task.addStages(builder, stagesOffset);
  Task.addArtifacts(builder, artifactsOffset);
  return Task.endTask(builder);
}
}
}
/**
 * @constructor
 */
export namespace schema{
export class GetResult {
  bb: flatbuffers.ByteBuffer|null = null;

  bb_pos:number = 0;
/**
 * @param number i
 * @param flatbuffers.ByteBuffer bb
 * @returns GetResult
 */
__init(i:number, bb:flatbuffers.ByteBuffer):GetResult {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param GetResult= obj
 * @returns GetResult
 */
static getRootAsGetResult(bb:flatbuffers.ByteBuffer, obj?:GetResult):GetResult {
  return (obj || new GetResult()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param GetResult= obj
 * @returns GetResult
 */
static getSizePrefixedRootAsGetResult(bb:flatbuffers.ByteBuffer, obj?:GetResult):GetResult {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new GetResult()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param number index
 * @param flatbuffers.Encoding= optionalEncoding
 * @returns string|Uint8Array
 */
idList(index: number):string
idList(index: number,optionalEncoding:flatbuffers.Encoding):string|Uint8Array
idList(index: number,optionalEncoding?:any):string|Uint8Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb!.__vector(this.bb_pos + offset) + index * 4, optionalEncoding) : null;
};

/**
 * @returns number
 */
idListLength():number {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @param flatbuffers.Builder builder
 */
static startGetResult(builder:flatbuffers.Builder) {
  builder.startObject(1);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset idListOffset
 */
static addIdList(builder:flatbuffers.Builder, idListOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, idListOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param Array.<flatbuffers.Offset> data
 * @returns flatbuffers.Offset
 */
static createIdListVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]);
  }
  return builder.endVector();
};

/**
 * @param flatbuffers.Builder builder
 * @param number numElems
 */
static startIdListVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
};

/**
 * @param flatbuffers.Builder builder
 * @returns flatbuffers.Offset
 */
static endGetResult(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

static createGetResult(builder:flatbuffers.Builder, idListOffset:flatbuffers.Offset):flatbuffers.Offset {
  GetResult.startGetResult(builder);
  GetResult.addIdList(builder, idListOffset);
  return GetResult.endGetResult(builder);
}
}
}
/**
 * @constructor
 */
export namespace schema{
export class GetHardwarePool {
  bb: flatbuffers.ByteBuffer|null = null;

  bb_pos:number = 0;
/**
 * @param number i
 * @param flatbuffers.ByteBuffer bb
 * @returns GetHardwarePool
 */
__init(i:number, bb:flatbuffers.ByteBuffer):GetHardwarePool {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param GetHardwarePool= obj
 * @returns GetHardwarePool
 */
static getRootAsGetHardwarePool(bb:flatbuffers.ByteBuffer, obj?:GetHardwarePool):GetHardwarePool {
  return (obj || new GetHardwarePool()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param GetHardwarePool= obj
 * @returns GetHardwarePool
 */
static getSizePrefixedRootAsGetHardwarePool(bb:flatbuffers.ByteBuffer, obj?:GetHardwarePool):GetHardwarePool {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new GetHardwarePool()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param number index
 * @param flatbuffers.Encoding= optionalEncoding
 * @returns string|Uint8Array
 */
hardware(index: number):string
hardware(index: number,optionalEncoding:flatbuffers.Encoding):string|Uint8Array
hardware(index: number,optionalEncoding?:any):string|Uint8Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb!.__vector(this.bb_pos + offset) + index * 4, optionalEncoding) : null;
};

/**
 * @returns number
 */
hardwareLength():number {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @param flatbuffers.Builder builder
 */
static startGetHardwarePool(builder:flatbuffers.Builder) {
  builder.startObject(1);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset hardwareOffset
 */
static addHardware(builder:flatbuffers.Builder, hardwareOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, hardwareOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param Array.<flatbuffers.Offset> data
 * @returns flatbuffers.Offset
 */
static createHardwareVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]);
  }
  return builder.endVector();
};

/**
 * @param flatbuffers.Builder builder
 * @param number numElems
 */
static startHardwareVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
};

/**
 * @param flatbuffers.Builder builder
 * @returns flatbuffers.Offset
 */
static endGetHardwarePool(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

static createGetHardwarePool(builder:flatbuffers.Builder, hardwareOffset:flatbuffers.Offset):flatbuffers.Offset {
  GetHardwarePool.startGetHardwarePool(builder);
  GetHardwarePool.addHardware(builder, hardwareOffset);
  return GetHardwarePool.endGetHardwarePool(builder);
}
}
}
/**
 * @constructor
 */
export namespace schema{
export class File {
  bb: flatbuffers.ByteBuffer|null = null;

  bb_pos:number = 0;
/**
 * @param number i
 * @param flatbuffers.ByteBuffer bb
 * @returns File
 */
__init(i:number, bb:flatbuffers.ByteBuffer):File {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param File= obj
 * @returns File
 */
static getRootAsFile(bb:flatbuffers.ByteBuffer, obj?:File):File {
  return (obj || new File()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param File= obj
 * @returns File
 */
static getSizePrefixedRootAsFile(bb:flatbuffers.ByteBuffer, obj?:File):File {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new File()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param flatbuffers.Encoding= optionalEncoding
 * @returns string|Uint8Array|null
 */
filename():string|null
filename(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
filename(optionalEncoding?:any):string|Uint8Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @returns number
 */
packetnumber():number {
  var offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
};

/**
 * @returns boolean
 */
eof():boolean {
  var offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
};

/**
 * @param number index
 * @returns number
 */
data(index: number):number|null {
  var offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readUint8(this.bb!.__vector(this.bb_pos + offset) + index) : 0;
};

/**
 * @returns number
 */
dataLength():number {
  var offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @returns Uint8Array
 */
dataArray():Uint8Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? new Uint8Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
};

/**
 * @param flatbuffers.Builder builder
 */
static startFile(builder:flatbuffers.Builder) {
  builder.startObject(4);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset filenameOffset
 */
static addFilename(builder:flatbuffers.Builder, filenameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, filenameOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param number packetnumber
 */
static addPacketnumber(builder:flatbuffers.Builder, packetnumber:number) {
  builder.addFieldInt32(1, packetnumber, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param boolean eof
 */
static addEof(builder:flatbuffers.Builder, eof:boolean) {
  builder.addFieldInt8(2, +eof, +false);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset dataOffset
 */
static addData(builder:flatbuffers.Builder, dataOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, dataOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param Array.<number> data
 * @returns flatbuffers.Offset
 */
static createDataVector(builder:flatbuffers.Builder, data:number[]|Uint8Array):flatbuffers.Offset {
  builder.startVector(1, data.length, 1);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addInt8(data[i]);
  }
  return builder.endVector();
};

/**
 * @param flatbuffers.Builder builder
 * @param number numElems
 */
static startDataVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(1, numElems, 1);
};

/**
 * @param flatbuffers.Builder builder
 * @returns flatbuffers.Offset
 */
static endFile(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

static createFile(builder:flatbuffers.Builder, filenameOffset:flatbuffers.Offset, packetnumber:number, eof:boolean, dataOffset:flatbuffers.Offset):flatbuffers.Offset {
  File.startFile(builder);
  File.addFilename(builder, filenameOffset);
  File.addPacketnumber(builder, packetnumber);
  File.addEof(builder, eof);
  File.addData(builder, dataOffset);
  return File.endFile(builder);
}
}
}
/**
 * @constructor
 */
export namespace schema{
export class Hardware {
  bb: flatbuffers.ByteBuffer|null = null;

  bb_pos:number = 0;
/**
 * @param number i
 * @param flatbuffers.ByteBuffer bb
 * @returns Hardware
 */
__init(i:number, bb:flatbuffers.ByteBuffer):Hardware {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param Hardware= obj
 * @returns Hardware
 */
static getRootAsHardware(bb:flatbuffers.ByteBuffer, obj?:Hardware):Hardware {
  return (obj || new Hardware()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param Hardware= obj
 * @returns Hardware
 */
static getSizePrefixedRootAsHardware(bb:flatbuffers.ByteBuffer, obj?:Hardware):Hardware {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Hardware()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param flatbuffers.Encoding= optionalEncoding
 * @returns string|Uint8Array|null
 */
cpu():string|null
cpu(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
cpu(optionalEncoding?:any):string|Uint8Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param flatbuffers.Encoding= optionalEncoding
 * @returns string|Uint8Array|null
 */
gpu():string|null
gpu(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
gpu(optionalEncoding?:any):string|Uint8Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param flatbuffers.Encoding= optionalEncoding
 * @returns string|Uint8Array|null
 */
os():string|null
os(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
os(optionalEncoding?:any):string|Uint8Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param flatbuffers.Encoding= optionalEncoding
 * @returns string|Uint8Array|null
 */
ram():string|null
ram(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
ram(optionalEncoding?:any):string|Uint8Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param flatbuffers.Builder builder
 */
static startHardware(builder:flatbuffers.Builder) {
  builder.startObject(4);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset cpuOffset
 */
static addCpu(builder:flatbuffers.Builder, cpuOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, cpuOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset gpuOffset
 */
static addGpu(builder:flatbuffers.Builder, gpuOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, gpuOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset osOffset
 */
static addOs(builder:flatbuffers.Builder, osOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, osOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset ramOffset
 */
static addRam(builder:flatbuffers.Builder, ramOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, ramOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @returns flatbuffers.Offset
 */
static endHardware(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

static createHardware(builder:flatbuffers.Builder, cpuOffset:flatbuffers.Offset, gpuOffset:flatbuffers.Offset, osOffset:flatbuffers.Offset, ramOffset:flatbuffers.Offset):flatbuffers.Offset {
  Hardware.startHardware(builder);
  Hardware.addCpu(builder, cpuOffset);
  Hardware.addGpu(builder, gpuOffset);
  Hardware.addOs(builder, osOffset);
  Hardware.addRam(builder, ramOffset);
  return Hardware.endHardware(builder);
}
}
}
/**
 * @constructor
 */
export namespace schema{
export class ResultList {
  bb: flatbuffers.ByteBuffer|null = null;

  bb_pos:number = 0;
/**
 * @param number i
 * @param flatbuffers.ByteBuffer bb
 * @returns ResultList
 */
__init(i:number, bb:flatbuffers.ByteBuffer):ResultList {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param ResultList= obj
 * @returns ResultList
 */
static getRootAsResultList(bb:flatbuffers.ByteBuffer, obj?:ResultList):ResultList {
  return (obj || new ResultList()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param ResultList= obj
 * @returns ResultList
 */
static getSizePrefixedRootAsResultList(bb:flatbuffers.ByteBuffer, obj?:ResultList):ResultList {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ResultList()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param number index
 * @param schema.Result= obj
 * @returns schema.Result
 */
tasks(index: number, obj?:schema.Result):schema.Result|null {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new schema.Result()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
};

/**
 * @returns number
 */
tasksLength():number {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @param flatbuffers.Builder builder
 */
static startResultList(builder:flatbuffers.Builder) {
  builder.startObject(1);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset tasksOffset
 */
static addTasks(builder:flatbuffers.Builder, tasksOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, tasksOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param Array.<flatbuffers.Offset> data
 * @returns flatbuffers.Offset
 */
static createTasksVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]);
  }
  return builder.endVector();
};

/**
 * @param flatbuffers.Builder builder
 * @param number numElems
 */
static startTasksVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
};

/**
 * @param flatbuffers.Builder builder
 * @returns flatbuffers.Offset
 */
static endResultList(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

static createResultList(builder:flatbuffers.Builder, tasksOffset:flatbuffers.Offset):flatbuffers.Offset {
  ResultList.startResultList(builder);
  ResultList.addTasks(builder, tasksOffset);
  return ResultList.endResultList(builder);
}
}
}
/**
 * @constructor
 */
export namespace schema{
export class Result {
  bb: flatbuffers.ByteBuffer|null = null;

  bb_pos:number = 0;
/**
 * @param number i
 * @param flatbuffers.ByteBuffer bb
 * @returns Result
 */
__init(i:number, bb:flatbuffers.ByteBuffer):Result {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param Result= obj
 * @returns Result
 */
static getRootAsResult(bb:flatbuffers.ByteBuffer, obj?:Result):Result {
  return (obj || new Result()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param Result= obj
 * @returns Result
 */
static getSizePrefixedRootAsResult(bb:flatbuffers.ByteBuffer, obj?:Result):Result {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Result()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns number
 */
time():number {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
};

/**
 * @param number index
 * @param schema.StageResult= obj
 * @returns schema.StageResult
 */
stages(index: number, obj?:schema.StageResult):schema.StageResult|null {
  var offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new schema.StageResult()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
};

/**
 * @returns number
 */
stagesLength():number {
  var offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @param number index
 * @param schema.Artifact= obj
 * @returns schema.Artifact
 */
artifacts(index: number, obj?:schema.Artifact):schema.Artifact|null {
  var offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? (obj || new schema.Artifact()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
};

/**
 * @returns number
 */
artifactsLength():number {
  var offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @param schema.Hardware= obj
 * @returns schema.Hardware|null
 */
hardware(obj?:schema.Hardware):schema.Hardware|null {
  var offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? (obj || new schema.Hardware()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
};

/**
 * @param flatbuffers.Builder builder
 */
static startResult(builder:flatbuffers.Builder) {
  builder.startObject(4);
};

/**
 * @param flatbuffers.Builder builder
 * @param number time
 */
static addTime(builder:flatbuffers.Builder, time:number) {
  builder.addFieldInt32(0, time, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset stagesOffset
 */
static addStages(builder:flatbuffers.Builder, stagesOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, stagesOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param Array.<flatbuffers.Offset> data
 * @returns flatbuffers.Offset
 */
static createStagesVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]);
  }
  return builder.endVector();
};

/**
 * @param flatbuffers.Builder builder
 * @param number numElems
 */
static startStagesVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset artifactsOffset
 */
static addArtifacts(builder:flatbuffers.Builder, artifactsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, artifactsOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param Array.<flatbuffers.Offset> data
 * @returns flatbuffers.Offset
 */
static createArtifactsVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]);
  }
  return builder.endVector();
};

/**
 * @param flatbuffers.Builder builder
 * @param number numElems
 */
static startArtifactsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset hardwareOffset
 */
static addHardware(builder:flatbuffers.Builder, hardwareOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, hardwareOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @returns flatbuffers.Offset
 */
static endResult(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

}
}
/**
 * @constructor
 */
export namespace schema{
export class StageResult {
  bb: flatbuffers.ByteBuffer|null = null;

  bb_pos:number = 0;
/**
 * @param number i
 * @param flatbuffers.ByteBuffer bb
 * @returns StageResult
 */
__init(i:number, bb:flatbuffers.ByteBuffer):StageResult {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param StageResult= obj
 * @returns StageResult
 */
static getRootAsStageResult(bb:flatbuffers.ByteBuffer, obj?:StageResult):StageResult {
  return (obj || new StageResult()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param StageResult= obj
 * @returns StageResult
 */
static getSizePrefixedRootAsStageResult(bb:flatbuffers.ByteBuffer, obj?:StageResult):StageResult {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new StageResult()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param number index
 * @param schema.CommandResult= obj
 * @returns schema.CommandResult
 */
cmd(index: number, obj?:schema.CommandResult):schema.CommandResult|null {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new schema.CommandResult()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
};

/**
 * @returns number
 */
cmdLength():number {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @param flatbuffers.Encoding= optionalEncoding
 * @returns string|Uint8Array|null
 */
name():string|null
name(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
name(optionalEncoding?:any):string|Uint8Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param flatbuffers.Builder builder
 */
static startStageResult(builder:flatbuffers.Builder) {
  builder.startObject(2);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset cmdOffset
 */
static addCmd(builder:flatbuffers.Builder, cmdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, cmdOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param Array.<flatbuffers.Offset> data
 * @returns flatbuffers.Offset
 */
static createCmdVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]);
  }
  return builder.endVector();
};

/**
 * @param flatbuffers.Builder builder
 * @param number numElems
 */
static startCmdVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset nameOffset
 */
static addName(builder:flatbuffers.Builder, nameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, nameOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @returns flatbuffers.Offset
 */
static endStageResult(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

static createStageResult(builder:flatbuffers.Builder, cmdOffset:flatbuffers.Offset, nameOffset:flatbuffers.Offset):flatbuffers.Offset {
  StageResult.startStageResult(builder);
  StageResult.addCmd(builder, cmdOffset);
  StageResult.addName(builder, nameOffset);
  return StageResult.endStageResult(builder);
}
}
}
/**
 * @constructor
 */
export namespace schema{
export class CommandResult {
  bb: flatbuffers.ByteBuffer|null = null;

  bb_pos:number = 0;
/**
 * @param number i
 * @param flatbuffers.ByteBuffer bb
 * @returns CommandResult
 */
__init(i:number, bb:flatbuffers.ByteBuffer):CommandResult {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param CommandResult= obj
 * @returns CommandResult
 */
static getRootAsCommandResult(bb:flatbuffers.ByteBuffer, obj?:CommandResult):CommandResult {
  return (obj || new CommandResult()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param CommandResult= obj
 * @returns CommandResult
 */
static getSizePrefixedRootAsCommandResult(bb:flatbuffers.ByteBuffer, obj?:CommandResult):CommandResult {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new CommandResult()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param flatbuffers.Encoding= optionalEncoding
 * @returns string|Uint8Array|null
 */
cmd():string|null
cmd(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
cmd(optionalEncoding?:any):string|Uint8Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @returns number
 */
exit():number {
  var offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
};

/**
 * @param number index
 * @returns number
 */
stdout(index: number):number|null {
  var offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readUint8(this.bb!.__vector(this.bb_pos + offset) + index) : 0;
};

/**
 * @returns number
 */
stdoutLength():number {
  var offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @returns Uint8Array
 */
stdoutArray():Uint8Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? new Uint8Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
};

/**
 * @param number index
 * @returns number
 */
stderr(index: number):number|null {
  var offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readUint8(this.bb!.__vector(this.bb_pos + offset) + index) : 0;
};

/**
 * @returns number
 */
stderrLength():number {
  var offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @returns Uint8Array
 */
stderrArray():Uint8Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? new Uint8Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
};

/**
 * @param flatbuffers.Encoding= optionalEncoding
 * @returns string|Uint8Array|null
 */
os():string|null
os(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
os(optionalEncoding?:any):string|Uint8Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param flatbuffers.Encoding= optionalEncoding
 * @returns string|Uint8Array|null
 */
cpu():string|null
cpu(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
cpu(optionalEncoding?:any):string|Uint8Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param flatbuffers.Encoding= optionalEncoding
 * @returns string|Uint8Array|null
 */
gpu():string|null
gpu(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
gpu(optionalEncoding?:any):string|Uint8Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param flatbuffers.Encoding= optionalEncoding
 * @returns string|Uint8Array|null
 */
ram():string|null
ram(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
ram(optionalEncoding?:any):string|Uint8Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 18);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @returns number
 */
time():number {
  var offset = this.bb!.__offset(this.bb_pos, 20);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
};

/**
 * @param flatbuffers.Builder builder
 */
static startCommandResult(builder:flatbuffers.Builder) {
  builder.startObject(9);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset cmdOffset
 */
static addCmd(builder:flatbuffers.Builder, cmdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, cmdOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param number exit
 */
static addExit(builder:flatbuffers.Builder, exit:number) {
  builder.addFieldInt32(1, exit, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset stdoutOffset
 */
static addStdout(builder:flatbuffers.Builder, stdoutOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, stdoutOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param Array.<number> data
 * @returns flatbuffers.Offset
 */
static createStdoutVector(builder:flatbuffers.Builder, data:number[]|Uint8Array):flatbuffers.Offset {
  builder.startVector(1, data.length, 1);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addInt8(data[i]);
  }
  return builder.endVector();
};

/**
 * @param flatbuffers.Builder builder
 * @param number numElems
 */
static startStdoutVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(1, numElems, 1);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset stderrOffset
 */
static addStderr(builder:flatbuffers.Builder, stderrOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, stderrOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param Array.<number> data
 * @returns flatbuffers.Offset
 */
static createStderrVector(builder:flatbuffers.Builder, data:number[]|Uint8Array):flatbuffers.Offset {
  builder.startVector(1, data.length, 1);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addInt8(data[i]);
  }
  return builder.endVector();
};

/**
 * @param flatbuffers.Builder builder
 * @param number numElems
 */
static startStderrVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(1, numElems, 1);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset osOffset
 */
static addOs(builder:flatbuffers.Builder, osOffset:flatbuffers.Offset) {
  builder.addFieldOffset(4, osOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset cpuOffset
 */
static addCpu(builder:flatbuffers.Builder, cpuOffset:flatbuffers.Offset) {
  builder.addFieldOffset(5, cpuOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset gpuOffset
 */
static addGpu(builder:flatbuffers.Builder, gpuOffset:flatbuffers.Offset) {
  builder.addFieldOffset(6, gpuOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset ramOffset
 */
static addRam(builder:flatbuffers.Builder, ramOffset:flatbuffers.Offset) {
  builder.addFieldOffset(7, ramOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param number time
 */
static addTime(builder:flatbuffers.Builder, time:number) {
  builder.addFieldInt32(8, time, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @returns flatbuffers.Offset
 */
static endCommandResult(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

static createCommandResult(builder:flatbuffers.Builder, cmdOffset:flatbuffers.Offset, exit:number, stdoutOffset:flatbuffers.Offset, stderrOffset:flatbuffers.Offset, osOffset:flatbuffers.Offset, cpuOffset:flatbuffers.Offset, gpuOffset:flatbuffers.Offset, ramOffset:flatbuffers.Offset, time:number):flatbuffers.Offset {
  CommandResult.startCommandResult(builder);
  CommandResult.addCmd(builder, cmdOffset);
  CommandResult.addExit(builder, exit);
  CommandResult.addStdout(builder, stdoutOffset);
  CommandResult.addStderr(builder, stderrOffset);
  CommandResult.addOs(builder, osOffset);
  CommandResult.addCpu(builder, cpuOffset);
  CommandResult.addGpu(builder, gpuOffset);
  CommandResult.addRam(builder, ramOffset);
  CommandResult.addTime(builder, time);
  return CommandResult.endCommandResult(builder);
}
}
}
/**
 * @constructor
 */
export namespace schema{
export class Artifact {
  bb: flatbuffers.ByteBuffer|null = null;

  bb_pos:number = 0;
/**
 * @param number i
 * @param flatbuffers.ByteBuffer bb
 * @returns Artifact
 */
__init(i:number, bb:flatbuffers.ByteBuffer):Artifact {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param Artifact= obj
 * @returns Artifact
 */
static getRootAsArtifact(bb:flatbuffers.ByteBuffer, obj?:Artifact):Artifact {
  return (obj || new Artifact()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param Artifact= obj
 * @returns Artifact
 */
static getSizePrefixedRootAsArtifact(bb:flatbuffers.ByteBuffer, obj?:Artifact):Artifact {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Artifact()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param flatbuffers.Encoding= optionalEncoding
 * @returns string|Uint8Array|null
 */
fileName():string|null
fileName(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
fileName(optionalEncoding?:any):string|Uint8Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param number index
 * @returns number
 */
data(index: number):number|null {
  var offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint8(this.bb!.__vector(this.bb_pos + offset) + index) : 0;
};

/**
 * @returns number
 */
dataLength():number {
  var offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @returns Uint8Array
 */
dataArray():Uint8Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? new Uint8Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
};

/**
 * @param flatbuffers.Builder builder
 */
static startArtifact(builder:flatbuffers.Builder) {
  builder.startObject(2);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset fileNameOffset
 */
static addFileName(builder:flatbuffers.Builder, fileNameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, fileNameOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset dataOffset
 */
static addData(builder:flatbuffers.Builder, dataOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, dataOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param Array.<number> data
 * @returns flatbuffers.Offset
 */
static createDataVector(builder:flatbuffers.Builder, data:number[]|Uint8Array):flatbuffers.Offset {
  builder.startVector(1, data.length, 1);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addInt8(data[i]);
  }
  return builder.endVector();
};

/**
 * @param flatbuffers.Builder builder
 * @param number numElems
 */
static startDataVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(1, numElems, 1);
};

/**
 * @param flatbuffers.Builder builder
 * @returns flatbuffers.Offset
 */
static endArtifact(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

static createArtifact(builder:flatbuffers.Builder, fileNameOffset:flatbuffers.Offset, dataOffset:flatbuffers.Offset):flatbuffers.Offset {
  Artifact.startArtifact(builder);
  Artifact.addFileName(builder, fileNameOffset);
  Artifact.addData(builder, dataOffset);
  return Artifact.endArtifact(builder);
}
}
}
