// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package HelloWorld

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type HelloWorld struct {
	_tab flatbuffers.Table
}

func GetRootAsHelloWorld(buf []byte, offset flatbuffers.UOffsetT) *HelloWorld {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &HelloWorld{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *HelloWorld) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *HelloWorld) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *HelloWorld) Msg() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func HelloWorldStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func HelloWorldAddMsg(builder *flatbuffers.Builder, msg flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(msg), 0)
}
func HelloWorldEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
